# Generated by Django 6.0.6 on 2026-08-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='complete',
            field=models.BooleanField(default=True),
        ),
    ]
